---
- name: Install Systemd Exporter
  hosts: "Servers:!fedora"
  become: true

  roles:
    - role: prometheus.prometheus.systemd_exporter
      vars:
        systemd_exporter_version: "latest"
        systemd_exporter_web_listen_address: "0.0.0.0:9558"
        systemd_exporter_system_user: "systemd-exp"
        systemd_exporter_system_group: "systemd-exp"
