name: Ansible Playbook Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Ansible and Ansible Lint
        run: |
          pip install ansible ansible-lint
          ansible-galaxy collection install ansible.posix

      - name: Run Ansible Lint
        run: |
          ansible-lint --exclude .github

      - name: Run Ansible Playbook Syntax Check
        run: |
          find . -name "*.yml" -not -path "./.github/workflows/*" -not -path "**/vars/*.yml" -not -path "**/tasks/*.yml" -not -name "requirements.yml" -print0 | xargs -0 -I {} ansible-playbook --syntax-check {}
